package controlador;
// Generated 17/05/2016 05:07:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private int idlibro;
     private Usuario usuario;
     private String nombre;
     private String autor;
     private String genero;
     private String editorial;
     private String pais;
     private String descripcion;
     private String fotoLibro;
     private Set solicitudeses = new HashSet(0);
     private Set calificacionlibros = new HashSet(0);

    public Libro() {
    }

	
    public Libro(int idlibro) {
        this.idlibro = idlibro;
    }
    public Libro(int idlibro, Usuario usuario, String nombre, String autor, String genero, String editorial, String pais, String descripcion, String fotoLibro, Set solicitudeses, Set calificacionlibros) {
       this.idlibro = idlibro;
       this.usuario = usuario;
       this.nombre = nombre;
       this.autor = autor;
       this.genero = genero;
       this.editorial = editorial;
       this.pais = pais;
       this.descripcion = descripcion;
       this.fotoLibro = fotoLibro;
       this.solicitudeses = solicitudeses;
       this.calificacionlibros = calificacionlibros;
    }
   
    public int getIdlibro() {
        return this.idlibro;
    }
    
    public void setIdlibro(int idlibro) {
        this.idlibro = idlibro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFotoLibro() {
        return this.fotoLibro;
    }
    
    public void setFotoLibro(String fotoLibro) {
        this.fotoLibro = fotoLibro;
    }
    public Set getSolicitudeses() {
        return this.solicitudeses;
    }
    
    public void setSolicitudeses(Set solicitudeses) {
        this.solicitudeses = solicitudeses;
    }
    public Set getCalificacionlibros() {
        return this.calificacionlibros;
    }
    
    public void setCalificacionlibros(Set calificacionlibros) {
        this.calificacionlibros = calificacionlibros;
    }




}


