package modelo;
// Generated 17/05/2016 05:07:52 PM by Hibernate Tools 4.3.1



/**
 * Calificacionusuario generated by hbm2java
 */
public class Calificacionusuario  implements java.io.Serializable {


     private int idcalificacionusr;
     private Usuario usuarioByPrestadoridusr;
     private Usuario usuarioByConsumidoridusr;
     private Integer calificacion;
     private String comentarios;

    public Calificacionusuario() {
    }

	
    public Calificacionusuario(int idcalificacionusr) {
        this.idcalificacionusr = idcalificacionusr;
    }
    public Calificacionusuario(int idcalificacionusr, Usuario usuarioByPrestadoridusr, Usuario usuarioByConsumidoridusr, Integer calificacion, String comentarios) {
       this.idcalificacionusr = idcalificacionusr;
       this.usuarioByPrestadoridusr = usuarioByPrestadoridusr;
       this.usuarioByConsumidoridusr = usuarioByConsumidoridusr;
       this.calificacion = calificacion;
       this.comentarios = comentarios;
    }
   
    public int getIdcalificacionusr() {
        return this.idcalificacionusr;
    }
    
    public void setIdcalificacionusr(int idcalificacionusr) {
        this.idcalificacionusr = idcalificacionusr;
    }
    public Usuario getUsuarioByPrestadoridusr() {
        return this.usuarioByPrestadoridusr;
    }
    
    public void setUsuarioByPrestadoridusr(Usuario usuarioByPrestadoridusr) {
        this.usuarioByPrestadoridusr = usuarioByPrestadoridusr;
    }
    public Usuario getUsuarioByConsumidoridusr() {
        return this.usuarioByConsumidoridusr;
    }
    
    public void setUsuarioByConsumidoridusr(Usuario usuarioByConsumidoridusr) {
        this.usuarioByConsumidoridusr = usuarioByConsumidoridusr;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


