package modelo;
// Generated 17/05/2016 05:07:52 PM by Hibernate Tools 4.3.1



/**
 * Calificacionlibro generated by hbm2java
 */
public class Calificacionlibro  implements java.io.Serializable {


     private int idcalificacionlibro;
     private Libro libro;
     private Usuario usuario;
     private Integer calificacion;
     private String comentario;

    public Calificacionlibro() {
    }

	
    public Calificacionlibro(int idcalificacionlibro) {
        this.idcalificacionlibro = idcalificacionlibro;
    }
    public Calificacionlibro(int idcalificacionlibro, Libro libro, Usuario usuario, Integer calificacion, String comentario) {
       this.idcalificacionlibro = idcalificacionlibro;
       this.libro = libro;
       this.usuario = usuario;
       this.calificacion = calificacion;
       this.comentario = comentario;
    }
   
    public int getIdcalificacionlibro() {
        return this.idcalificacionlibro;
    }
    
    public void setIdcalificacionlibro(int idcalificacionlibro) {
        this.idcalificacionlibro = idcalificacionlibro;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


